### ISSUE TITLE
[feature request] Get hires image when clicking on preview

### ISSUE THREAD

**Issue by palasinio** [werthdavid/homebridge-website-to-camera#19] opened 2020-04-21 19:05 UTC
Hi,

I have two questions:
1st: Why are there 3 to 4 chromium processes per cam running?
Is it possible to reduce that? Or is it possible to use the same chromium instance?
I haven't found anything in chromium config.

2nd: In Home app, if you tap on a picture it will enlarge to fullscreen, but there is no new image loaded in this view - just a loading wheel in the middle.

Do you see a chance to get images loaded (and maybe in better resolution) in this view?

kind regards,

**Comment by werthdavid** [comment] 2020-04-26 14:33
1) I have to look into that but usually every chrome tab gets at least one process plus one for the master window. 
2) I fear I can’t do much about that. The problem is that HomeKit expects an address for a stream where it can connect to (rtsp) to display the video in full screen. I have not found a solution (maybe addon?) that provides an endpoint for an rtsp stream where you can connect to for a video...

**Comment by palasinio** [comment] 2020-04-26 15:27
> 2\. The problem is that HomeKit expects an address for a stream where it can connect to (rtsp) to display the video in full screen.

Ah, okay - I didn‘t knew that.

**Comment by werthdavid** [comment] 2020-04-27 07:21
1. Also something I cannot do much about. Every cam is an own accessory that is isolated from the others that starts its own Chrome browser. Due to the sandbox-mechanism the memory/cpu overhead should not be much higher than using a single master-instance since Chrome starts new tasks for each tab anyway.

I will close this for now, if something changes we can re-open this.

**Closed as completed by werthdavid** 2020-04-27 07:21 UTC
Labels: question
